// <auto-generated />
namespace CruscottoIncidenti.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddManyToManyRelatioshipForUsersAndRoles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddManyToManyRelatioshipForUsersAndRoles));
        
        string IMigrationMetadata.Id
        {
            get { return "202601191443429_AddManyToManyRelatioshipForUsersAndRoles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
